apiVersion: apps/v1
kind: Deployment 
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
      tier: frontend
  template:
    metadata:
      labels:
        app: app
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: example/frontend:latest
        imagePullPolicy: "Always"
        lifecycle:
          preStop:
            exec:
              command: ["/usr/sbin/nginx","-s","quit"]
